name = "autocar-lab-worker"
main = "./dist/index.mjs"
compatibility_date = "2022-09-08"
services = [
    { binding = "USER", service = "autocar-user-worker", environment = "production" },
    { binding = "TEAM", service = "autocar-team-worker", environment = "production" },
]

[build]
command = "yarn build"


[durable_objects]
bindings = [{name = "STORAGE", class_name = "StorageDO"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["StorageDO"]