name = "autocar-room-worker"
main = "./dist/index.mjs"
compatibility_date = "2022-09-08"

[build]
command = "yarn build"

[[services]]
binding = "USER"
service = "autocar-user-worker"
environment = "production"

[durable_objects]
bindings = [{name = "STORAGE", class_name = "StorageDO"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["StorageDO"]